# Generated by Django 5.0 on 2024-05-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='social_profiles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
