# Generated by Django 5.0 on 2024-05-09 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('company', 'Company'), ('college', 'College')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, choices=[('BTECH', 'B.Tech'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('BSC', 'B.Sc.'), ('BDES', 'B.Des')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('courses', models.TextField()),
                ('tnp_cell_contact', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('number_of_students', models.IntegerField()),
                ('social_profile', models.URLField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('description', models.TextField()),
                ('employees', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
