# Generated by Django 5.0 on 2024-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_collegeuser_companyuser_remove_companyprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
