# Generated by Django 5.0 on 2024-05-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='location',
            new_name='university',
        ),
        migrations.RemoveField(
            model_name='college',
            name='description',
        ),
        migrations.RemoveField(
            model_name='college',
            name='ranking',
        ),
    ]
